%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam;
imu: 1
num_of_cam: 2


imu_topic: "/camera/imu"
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"
output_path: "/home/seungwon/.ros/dynaVINS"

cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 640
image_height: 480


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [  0.99995065, -0.00448684,  0.00886397, -0.03341319,
       0.00447312,  0.99998877,  0.00156799,  0.00350357 ,
        -0.00887091, -0.00152826,  0.99995948,  0.02122639,
       0., 0., 0., 1. ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.99998534, -0.00438068,  0.00318378,  0.06154326,
       0.00437405,  0.99998826,  0.0020868,   0.00394544 ,
        -0.00319288, -0.00207284,  0.99999275,  0.02056234,
       0., 0., 0., 1. ]


#Multiple thread support
multiple_thread: 1


#feature traker paprameters
max_cnt: 300            # max feature number in feature tracking
min_dist: 10            # min distance between two features
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
F_threshold: 1.0        # ransac threshold (pixel)
max_depth: 10.0         # max estimated depth (m)

show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#vins parameter for revision
switchable_on:  0.0
switchable_gamma: 1.0

#optimization parameters
max_solver_time: 0.2  # max solver itration time (ms), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.278568031016           # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.024937606912         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.000827382177682         # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 1.71512255197e-05       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805         # gravity magnitude


#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.00098394134518773            # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
max_keyframe : 20

min_loop : 15.0
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/seungwon/.ros/dynaVINS" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0

